### ISSUE TITLE
Request Clearing a Channel Subscription

### ISSUE THREAD

**Issue by Markola100** [bitfocus/companion-module-audinate-dante-ddm#3]
It is possible to clear a subscription? I have the option of subscribing to a channel at the push of a button, it would also be very helpful to clear a subscription. Some devices only have a limited number of flows.

**Comment by jamesabbottsmith** [comment]
Sorry this has taken so long to respond to you.

Set the Tx device and Tx channel to empty strings to clear subscriptions on an Rx channel.

I tend to create a button labelled "Clear" with Tx device & Tx channel set to empty strings. 

We've also added this to the help document to make that clearer for others.
