### ISSUE TITLE
Certificate Error

### ISSUE THREAD

**Issue by jgrudolph** [bitfocus/companion-module-audinate-dante-ddm#4]
When trying to connect, I get the error: ApolloError: request to https://(my domain)/graphql failed, reason: unable to verify the first certificate.  Have been able to connect in postman successfully from the same system.

**Comment by barraliddy** [comment]
Having exactly the same issue. Successfully connecting to DDM using postman, however companion cannot connect and gives the same error message "https://(my domain)/graphql failed, reason: unable to verify the first certificate".
Did you make any progress on this?

**Comment by benthere79** [comment]
Similar issue, using an internal enterprise certficate chain, error is:
 Disconnected ApolloError: request to _FQDN_ failed,reason: self-signed certificate in certificate chain

**Comment by phillipivan** [comment]
We are encountering the same error. We have the local cert installed on the machine and can reach DDM via Chrome without a cert error.

```
Creating ApolloClient
Getting list of available Domains
[Network error]: {
  "message": "request to https://ddm.xxx.xxx.xxx.xxx/graphql failed, reason: unable to verify the first certificate",
  "type": "system",
  "errno": "UNABLE_TO_VERIFY_LEAF_SIGNATURE",
  "code": "UNABLE_TO_VERIFY_LEAF_SIGNATURE"
}
```

**Comment by barraliddy** [comment]
After some back and forth with Audinate, it seems that the DDM API is only accessible when using a public CA, rather than a self-signed or internal CA. After purchasing a public CA we had no certificate errors and accessing DDM via Companion was successful.

**Comment by phillipivan** [comment]
What a disappointing response.

**Comment by jamesabbottsmith** [comment]
I'm sorry it has taken so long to get back to you, and it wasn't the response from support that you were looking for.

Whilst there's a benefit in using a trusted CA-signed certificate, I understand that it typically costs money and isn't always required.

We've just updated the module so that there is the option to disable certificate validation. This will allow you to connect to your DDM using your self-signed certificate. 

![Image](https://github.com/user-attachments/assets/228bc7b4-bcc8-4a16-9a56-1185c56e4b60)

**Comment by phillipivan** [comment]
Thanks so much for this change James. FWIW it isn't the case that we are using self signed certificates. Rather we have an inhouse CA, which is used for internal only services, like DDM. The root certificate is installed on the server running Companion, but Companion cant (yet) access those root certification to validate the cert.

**Comment by JuddiP** [comment]
Hey @jamesabbottsmith, copying in information from a comment I made on the [last commit ](https://github.com/bitfocus/companion-module-audinate-dante-ddm/commit/6a657f5cd5feade5ae2a85755637dce55e0ba58c#commitcomment-148860107).

I have tried to test this new commit by running it in dev mode. The module is crashing when I attempt to restart the connection (after entering in my site's particular DDM details).

> system: ** Starting Connection from "C:\Support\companion-modules-dev\companion-module-audinate-ddm_v110\main.js" **
> system: ** Connection started **
> Starting up module class: AudinateDanteModule
> Sentry disabled
> Module-host accepted registration
> Creating ApolloClient
> Getting list of available Domains
> **error: Failed to init: Error: Call timed out Error: Call timed out
> at t.IpcWrapper.sendWithCb (C:\Program Files\Companion\resources\main.js:2:2687051)
> at T.init (C:\Program Files\Companion\resources\main.js:2:3131614)
> at l.s (C:\Program Files\Companion\resources\main.js:2:3143472)
> at l.emit (node:events:517:28)
> at ChildProcess. (C:\Program Files\Companion\resources\main.js:2:2673563)
> at ChildProcess.emit (node:events:517:28)
> at emit (node:internal/child_process:944:14)
> at process.processTicksAndRejections (node:internal/process/task_queues:83:21)**
> system: ** Connection stopped **

It just continues to loop this error state.

**Comment by jamesabbottsmith** [comment]
@JuddiP - We're looking into this now. We'll get back to you ASAP. 

To clarify, was this module working for you before the latest update?

**Comment by phillipivan** [comment]
@jamesabbottsmith yes I agree that doing it at Companion level makes much more sense than per module (hence the feature request), and would solve issues in a few other places than just DDM for us.

I pulled the repo and built the module @JuddiP  is trying to use with Companion 3.4.3. Previously the module hasn't crashed, but we also haven't been able to do anything because of this issue, so we were keen to test it out. I have made a new build with the `yarn companion-module-build --dev` flag enabled to see if we get more descriptive log entries.

**Comment by JuddiP** [comment]
Hi @jamesabbottsmith,

Ended up finding the **cause of the error** -- a firewall policy was missing and blocking the Companion module from connecting to our DDM cluster. I wouldn't have expected the module to crash though -- perhaps some further error handling is required?

**Comment by jamesabbottsmith** [comment]
Hi @JuddiP,

We've just pushed v1.1.1, which adds better handling when there is a network error. The module shouldn't crash anymore, it just should just keep retrying until the server becomes available again. Hopefully that leads to a much better experience.

I might close this ticket now as I think the certificate issue is resolved. Feel free to open more tickets / feature requests. We'll try to be *much* more responsive than we were with this one. Thanks for your patience with us

**Comment by JuddiP** [comment]
Thanks for the update, @jamesabbottsmith.

No stress about the delay, we got there in the end!
